### ISSUE TITLE
Tekillik Kontrolü

### ISSUE THREAD

**Issue by coderserdar** [ferpven/MyLibraryConsole#2]
Yeni kitap eklerken kaydın daha önceden ekli olup olmadığının kontrolleri yapılmamış. Bunların eklenmesi gerekiyor. Güncelleme yaparken de benzer bir şekilde a ve b kitapları olduğunu düşünelim.
Eğer b adındaki kitabı da a yapmaya kalkarsa, bunda da kontrol olması lazım.
Tekillik kontrolü yazar adı + kitap adı olacak şekilde olabilir.
Bunda da case insensitive olmalı. Yani biri büyük harfli diğeri küçük harfli olduğu zaman ekleyememeli

**Comment by ferpven** [comment]
Yeni kitap ekleme için önerdiğiniz şekilde gerçekleştirdim sadece update fonksiyonu için benzer bir metodu tekrardan yazmam gerekti. Tekrardan yazmadan yapabileceğimi düşünmüyorum.
