### ISSUE TITLE
Modülerlik

### ISSUE THREAD

**Issue by coderserdar** [ferpven/MyLibraryConsole#4]
Switch case bloklarının içerisinde yer alan kod blokları mümkün oldukça metot haline getirilmeli, DRY prensiplerine uygun olacak şekilde benzer kod blokları da metot haline getirilmelidir.

**Comment by ferpven** [comment]
Kitap eklemeyi metoda taşıdım kodun okunurluğu açısından. DatabaseOperations dosyasında metot haline getirebileceğim ekstra bir şey göremedim.
